# Generated by Django 6.0.1 on 2026-01-22 01:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=75, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_image/', verbose_name='Изображение')),
                ('published_to', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('updated_to', models.DateTimeField(auto_now_add=True, verbose_name='Отредактировано в ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
