# Generated by Django 6.0.1 on 2026-01-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_to'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
