# Generated by Django 6.0.1 on 2026-01-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_db', '0003_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Роль'),
        ),
    ]
