# Generated by Django 6.0.1 on 2026-01-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_app', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО обращавшегося')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('theme', models.CharField(choices=[('general', 'Общий вопрос'), ('editorial', 'Редакция'), ('advertising', 'Реклама'), ('support', 'Техподдержка'), ('cooperation', 'Сотрудничество'), ('other', 'Другое')], default='general', max_length=50, verbose_name='Тема обращения')),
                ('custom_theme', models.CharField(blank=True, max_length=100, verbose_name="Своя тема (если выбрано 'Другое')")),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус обращения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
    ]
